name: composable_diffusion
model: composable_diffusion
version: runwayml/stable-diffusion-v1-5
scheduler: ddim
params:
  height: 512
  width: 512
  num_inference_steps: 50
  guidance_scale: 7.5
  eta: 0.0
  guidance_rescale: 0.0
  return_dict: True
  output_type: pil
