name: ours
model: ours
version: runwayml/stable-diffusion-v1-5
scheduler: ddim
params:
  height: 512
  width: 512
  num_inference_steps: 50
  guidance_scale: 7.5

vis_option:
  down:
    level: [0]
    head: 0
  mid:
    level: [0]
    head: 0
  up:
    level: [0]
    head: 0